/* ──────────────────────────────────────────────
   Report generation: PDF (print) and TXT
   ────────────────────────────────────────────── */

const REPORT_I18N = {
    ru: {
        situation: 'Ситуация',
        thought: 'Мысль',
        emotion: 'Эмоция',
        rationalResponse: 'Рациональный ответ',

        activityDone: '✓ Выполнено',
        activityPlanned: '○ В плане',

        reportTitle: 'КПТ-выписка',
        reportSubtitle: 'Дневник мыслей · Настроение · Сон · Активности',
        autoReport: 'Автоматический отчёт',

        avgMood14: 'Среднее настроение (14 д.)',
        avgSleep7: 'Среднее время сна (7 д.)',
        activitiesDone: 'Активностей выполнено',
        lastPHQ: 'PHQ-9 (последний)',

        moodRecent: 'Настроение — последние {count} записей',
        sleepRecent: 'Сон — последние {count} дней',
        thoughtRecent: 'Дневник мыслей (последние {count} записей)',

        noRecords: 'Записей нет',

        testResults: 'Результаты тестов',
        test: 'Тест',
        date: 'Дата',
        score: 'Балл',
        interpretation: 'Интерпретация',

        activities: 'Активности',
        task: 'Задача',
        status: 'Статус',

        footer: 'Сформировано КПТ-ассистентом · Не является медицинским заключением',

        savePDF: '↓ Сохранить как PDF',
        savePDFHint: 'Выберите «Сохранить как PDF» в диалоге печати',

        mood: 'Настроение',
        sleepHours: 'Часы сна',
        quality: 'Качество',
        hoursAxis: 'Часы',
        qualityAxis: 'Качество',

        hourSuffix: 'ч'
    },

    en: {
        situation: 'Situation',
        thought: 'Automatic thought',
        emotion: 'Emotion',
        rationalResponse: 'Balanced response',

        activityDone: '✓ Completed',
        activityPlanned: '○ Planned',

        reportTitle: 'CBT Report',
        reportSubtitle: 'Thought Diary · Mood · Sleep · Activities',
        autoReport: 'Automatic report',

        avgMood14: 'Average mood (14 days)',
        avgSleep7: 'Average sleep (7 days)',
        activitiesDone: 'Activities completed',
        lastPHQ: 'PHQ-9 (latest)',

        moodRecent: 'Mood — latest {count} entries',
        sleepRecent: 'Sleep — latest {count} days',
        thoughtRecent: 'Thought diary (latest {count} entries)',

        noRecords: 'No records',

        testResults: 'Assessment results',
        test: 'Test',
        date: 'Date',
        score: 'Score',
        interpretation: 'Interpretation',

        activities: 'Activities',
        task: 'Task',
        status: 'Status',

        footer: 'Generated by CBT Assistant · Not a medical diagnosis',

        savePDF: '↓ Save as PDF',
        savePDFHint: 'Choose “Save as PDF” in the print dialog',

        mood: 'Mood',
        sleepHours: 'Sleep hours',
        quality: 'Quality',
        hoursAxis: 'Hours',
        qualityAxis: 'Quality',

        hourSuffix: 'h'
    },

    zh: {
        situation: '情境',
        thought: '自动化想法',
        emotion: '情绪',
        rationalResponse: '平衡想法',

        activityDone: '✓ 已完成',
        activityPlanned: '○ 计划中',

        reportTitle: 'CBT 心理记录报告',
        reportSubtitle: '思维日记 · 情绪 · 睡眠 · 活动',
        autoReport: '自动生成报告',

        avgMood14: '平均情绪（14天）',
        avgSleep7: '平均睡眠时间（7天）',
        activitiesDone: '已完成活动',
        lastPHQ: 'PHQ-9（最近一次）',

        moodRecent: '情绪记录——最近 {count} 条',
        sleepRecent: '睡眠记录——最近 {count} 天',
        thoughtRecent: '思维日记（最近 {count} 条）',

        noRecords: '暂无记录',

        testResults: '心理测试结果',
        test: '测试',
        date: '日期',
        score: '分数',
        interpretation: '结果说明',

        activities: '活动',
        task: '任务',
        status: '状态',

        footer: '由 CBT 心理助手自动生成 · 本报告不构成医学诊断',

        savePDF: '↓ 保存为 PDF',
        savePDFHint: '请在打印窗口中选择“另存为 PDF”或“保存为 PDF”',

        mood: '情绪',
        sleepHours: '睡眠时长',
        quality: '睡眠质量',
        hoursAxis: '小时',
        qualityAxis: '质量',

        hourSuffix: '小时'
    }
};


function getReportLanguage() {
    if (typeof window.getCurrentLanguage === 'function') {
        return window.getCurrentLanguage();
    }

    return localStorage.getItem('APP_LANG') || 'zh';
}


function getReportLocale() {
    const lang = getReportLanguage();

    if (lang === 'en') {
        return 'en-US';
    }

    if (lang === 'ru') {
        return 'ru-RU';
    }

    return 'zh-CN';
}


function reportText(key, params = {}) {
    const lang = getReportLanguage();

    let text =
        REPORT_I18N[lang]?.[key]
        ?? REPORT_I18N.zh[key]
        ?? REPORT_I18N.en[key]
        ?? key;

    Object.entries(params).forEach(([name, value]) => {
        text = text.replaceAll(`{${name}}`, value);
    });

    return text;
}

const reportEscapeHtml = value => window.CBTSecurity.escapeHtml(value);
const reportScriptValue = value => window.CBTSecurity.serializeForInlineScript(value);
   
function downloadAsTXT() {
    closeModal('downloadModal');

    const lang = getReportLanguage();

    window.open(
        API
        + '/api/report/'
        + SESSION_ID
        + '?lang='
        + encodeURIComponent(lang),
        '_blank'
    );
}

async function downloadAsPDF() {
    closeModal('downloadModal');

    const reportLocale = getReportLocale();
    const reportLang = getReportLanguage();

    // Collect all data
    const moodLog = JSON.parse(localStorage.getItem('moodLog') || '[]');
    const sleepLog = JSON.parse(localStorage.getItem('sleepLog') || '[]');
    const activities = JSON.parse(localStorage.getItem('activities') || '[]');
    const phqHist = JSON.parse(localStorage.getItem('phqHistory') || '[]');
    const gadHist = JSON.parse(localStorage.getItem('gadHistory') || '[]');

    let thoughts = [];
    try {
        const res = await fetch(API + '/api/thoughts/' + SESSION_ID).then(r => r.json());
        thoughts = res.thought_records || [];
    } catch (_) { }

    // Stats
    const avgMood = moodLog.length
        ? (moodLog.slice(-14).reduce((a, e) => a + e.score, 0) / Math.min(moodLog.length, 14)).toFixed(1)
        : null;
    const avgSleep = sleepLog.length
        ? (sleepLog.slice(-7).reduce((a, e) => a + parseFloat(e.durHrs || e.hours || 0), 0) / Math.min(sleepLog.length, 7)).toFixed(1)
        : null;
    const doneActs = activities.filter(a => a.done).length;
    const lastPHQ = phqHist.length ? phqHist[phqHist.length - 1] : null;
    const lastGAD = gadHist.length ? gadHist[gadHist.length - 1] : null;

    // Build mood chart data (last 14 entries)
    const moodRecent = [...moodLog].sort((a, b) => new Date(a.date) - new Date(b.date)).slice(-14);
    const moodLabels = moodRecent.map(e => {
        const d = new Date(e.date);
        return d.toLocaleDateString(reportLocale, { day: 'numeric', month: 'short' });
    });
    const moodScores = moodRecent.map(e => e.score);

    // Sleep chart data (last 7 entries)
    const sleepRecent = [...sleepLog].sort((a, b) => new Date(a.isoDate || 0) - new Date(b.isoDate || 0)).slice(-7);
    const sleepLabels = sleepRecent.map(e => {
        const d = new Date(e.isoDate || Date.now());
        return d.toLocaleDateString(reportLocale, { day: 'numeric', month: 'short' });
    });
    const sleepHours = sleepRecent.map(e => parseFloat(e.durHrs || e.hours || 0));
    const sleepQuality = sleepRecent.map(e => parseFloat(e.quality || 0));

    // Thought records (last 10)
    const thoughtsHTML = thoughts.slice(-10).reverse().map(r => {
        const d = new Date(r.timestamp);
        const dateStr = d.toLocaleDateString(reportLocale, { day: 'numeric', month: 'long' }) +
          ' · ' + d.toLocaleTimeString(reportLocale, { hour: '2-digit', minute: '2-digit' });
        return `
            <div class="thought-card">
                <div class="thought-date">${dateStr}</div>
                ${r.situation ? `<div class="field"><span class="label">${reportText('situation')}</span><span class="value">${reportEscapeHtml(r.situation)}</span></div>` : ''}
                ${r.thought ? `<div class="field"><span class="label">${reportText('thought')}</span><span class="value">${reportEscapeHtml(r.thought)}</span></div>` : ''}
                ${r.emotion ? `<div class="field"><span class="label">${reportText('emotion')}</span><span class="value">${reportEscapeHtml(r.emotion)}${r.intensity ? ' · ' + reportEscapeHtml(r.intensity) + '/10' : ''}</span></div>` : ''}
                ${r.rational_response ? `<div class="field"><span class="label">${reportText('rationalResponse')}</span><span class="value">${reportEscapeHtml(r.rational_response)}</span></div>` : ''}
                ${r.distortion ? `<div class="distortion-tag">${reportEscapeHtml(r.distortion)}</div>` : ''}
            </div>`;
    }).join('');

    // PHQ/GAD history rows
    const testRows = [...phqHist.map(e => ({ ...e, type: 'PHQ-9' })),
    ...gadHist.map(e => ({ ...e, type: 'GAD-7' }))]
        .sort((a, b) => new Date(b.date) - new Date(a.date))
        .slice(0, 10)
        .map(e => {
            const d = new Date(e.date);
            const dateStr = d.toLocaleDateString(reportLocale, {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
});
            return `<tr><td>${reportEscapeHtml(e.type)}</td><td>${reportEscapeHtml(dateStr)}</td><td><strong>${reportEscapeHtml(e.score)}</strong></td><td>${reportEscapeHtml(e.interpretation || '—')}</td></tr>`;
        }).join('');

    // Activities
    const actRows = activities.slice(-15).map(a =>
    `<tr><td>${reportEscapeHtml(a.text || a.activity_text || '—')}</td><td>${a.done ? reportText('activityDone') : reportText('activityPlanned')}</td></tr>`
    ).join('');

    const now = new Date();
    const reportDate = now.toLocaleDateString(reportLocale, {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
    });

const html = `<!DOCTYPE html>
<html lang="${reportEscapeHtml(reportLang)}">
<head>
<meta charset="UTF-8">
<title>${reportText('reportTitle')} · ${reportDate}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js"><\/script>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8f7f5; color: #1a1a2e; font-size: 13px; }
  .page { max-width: 820px; margin: 0 auto; padding: 40px 48px; }

  /* Header */
  .report-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 36px; padding-bottom: 20px; border-bottom: 2px solid #797298; }
  .report-title { font-size: 26px; font-weight: 700; color: #1a1a2e; }
  .report-subtitle { font-size: 13px; color: #888; margin-top: 4px; }
  .report-date { text-align: right; font-size: 12px; color: #888; }
  .report-badge { background: #797298; color: #fff; font-size: 11px; padding: 3px 10px; border-radius: 20px; display: inline-block; margin-top: 6px; }

  /* Stats */
  .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; margin-bottom: 36px; }
  .stat-card { background: #fff; border-radius: 12px; padding: 16px; border-left: 3px solid #797298; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
  .stat-val { font-size: 24px; font-weight: 700; color: #1a1a2e; }
  .stat-label { font-size: 11px; color: #888; margin-top: 3px; }

  /* Sections */
  .section { background: #fff; border-radius: 14px; padding: 24px; margin-bottom: 20px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
  .section-title { font-size: 14px; font-weight: 700; color: #1a1a2e; margin-bottom: 16px; display: flex; align-items: center; gap: 8px; padding-bottom: 10px; border-bottom: 1px solid #f0eef8; }
  .section-title::before { content: ''; display: inline-block; width: 4px; height: 16px; background: #797298; border-radius: 2px; }

  /* Thought cards */
  .thought-card { border: 1px solid #f0eef8; border-radius: 10px; padding: 14px 16px; margin-bottom: 12px; }
  .thought-card:last-child { margin-bottom: 0; }
  .thought-date { font-size: 11px; color: #888; margin-bottom: 10px; }
  .field { display: flex; gap: 8px; margin-bottom: 7px; font-size: 13px; }
  .label { min-width: 130px; font-weight: 600; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #aaa; padding-top: 2px; }
  .value { flex: 1; line-height: 1.55; color: #1a1a2e; }
  .distortion-tag { display: inline-block; background: #f0eef8; color: #797298; border-radius: 20px; padding: 3px 10px; font-size: 11px; margin-top: 6px; }

  /* Tables */
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #aaa; font-weight: 700; padding: 0 0 10px; border-bottom: 1px solid #f0eef8; }
  td { padding: 8px 0; border-bottom: 1px solid #f8f7f5; vertical-align: top; }
  tr:last-child td { border-bottom: none; }

  /* Charts */
  .chart-wrap { position: relative; height: 160px; margin-top: 8px; }

  /* Empty */
  .empty { color: #aaa; font-size: 13px; text-align: center; padding: 20px 0; }

  /* Footer */
  .report-footer { margin-top: 36px; padding-top: 16px; border-top: 1px solid #eee; font-size: 11px; color: #bbb; text-align: center; }

  /* Print */
  @media print {
    body { background: #fff; }
    .page { padding: 20px 30px; }
    .no-print { display: none !important; }
    .section { box-shadow: none; border: 1px solid #eee; page-break-inside: avoid; }
    .thought-card { page-break-inside: avoid; }
  }
</style>
</head>
<body>
<div class="page">

  <!-- Header -->
  <div class="report-header">
      <div>
        <div class="report-title">${reportText('reportTitle')}</div>
        <div class="report-subtitle">${reportText('reportSubtitle')}</div>
      </div>
      <div class="report-date">
        <div>${reportDate}</div>
        <div class="report-badge">${reportText('autoReport')}</div>
      </div>
  </div>

  <!-- Stats -->
  <div class="stats-grid">
    <div class="stat-card">
      <div class="stat-val">${avgMood ?? '—'}</div>
      <div class="stat-label">${reportText('avgMood14')}</div>
    </div>
    <div class="stat-card" style="border-left-color:#38bdf8;">
      <div class="stat-val">${avgSleep ? avgSleep + reportText('hourSuffix') : '—'}</div>
      <div class="stat-label">${reportText('avgSleep7')}</div>
    </div>
    <div class="stat-card" style="border-left-color:#10b981;">
      <div class="stat-val">${doneActs}</div>
      <div class="stat-label">${reportText('activitiesDone')}</div>
    </div>
    <div class="stat-card" style="border-left-color:${lastPHQ ? '#f59e0b' : '#ccc'};">
      <div class="stat-val">${lastPHQ ? reportEscapeHtml(lastPHQ.score) : '—'}</div>
      <div class="stat-label">${reportText('lastPHQ')}</div>
    </div>
  </div>

  <!-- Mood Chart -->
  ${moodScores.length >= 2 ? `
  <div class="section">
    <div class="section-title">${reportText('moodRecent', { count: moodScores.length })}</div>
    <div class="chart-wrap"><canvas id="moodChart"></canvas></div>
  </div>` : ''}

  <!-- Sleep Chart -->
  ${sleepHours.length >= 2 ? `
<div class="section">
    <div class="section-title">${reportText('sleepRecent', { count: sleepHours.length })}</div>
    <div class="chart-wrap"><canvas id="sleepChart"></canvas></div>
</div>` : ''}

  <!-- Thought diary -->
  <div class="section">
    <div class="section-title">${reportText('thoughtRecent', { count: Math.min(thoughts.length, 10) })}</div>
    ${thoughtsHTML || `<div class="empty">${reportText('noRecords')}</div>`}
</div>

  <!-- Tests -->
  ${testRows ? `
  <div class="section">
    <div class="section-title">${reportText('testResults')}</div>
    <table>
      <thead>
        <tr>
          <th>${reportText('test')}</th>
          <th>${reportText('date')}</th>
          <th>${reportText('score')}</th>
          <th>${reportText('interpretation')}</th>
        </tr>
      </thead>
      <tbody>${testRows}</tbody>
    </table>
  </div>` : ''}

  <!-- Activities -->
  ${actRows ? `
  <div class="section">
    <div class="section-title">${reportText('activities')}</div>
    <table>
      <thead>
        <tr>
          <th>${reportText('task')}</th>
          <th>${reportText('status')}</th>
        </tr>
      </thead>
      <tbody>${actRows}</tbody>
    </table>
  </div>` : ''}

<div class="report-footer">
    ${reportText('footer')}
</div>

<!-- Print button (hidden in print) -->
<div class="no-print" style="text-align:center;margin-top:28px;">
    <button onclick="window.print()" style="background:#797298;color:#fff;border:none;border-radius:24px;padding:12px 32px;font-size:14px;cursor:pointer;font-family:inherit;">
      ${reportText('savePDF')}
    </button>
    <p style="color:#aaa;font-size:11px;margin-top:8px;">${reportText('savePDFHint')}</p>
</div>

<script>
const MOOD_LABELS  = ${reportScriptValue(moodLabels)};
const MOOD_SCORES  = ${reportScriptValue(moodScores)};
const SLEEP_LABELS  = ${reportScriptValue(sleepLabels)};
const SLEEP_HOURS   = ${reportScriptValue(sleepHours)};
const SLEEP_QUALITY = ${reportScriptValue(sleepQuality)};

window.addEventListener('load', () => {
  if (MOOD_SCORES.length >= 2) {
    new Chart(document.getElementById('moodChart'), {
      type: 'line',
      data: {
        labels: MOOD_LABELS,
        datasets: [{
          label: ${reportScriptValue(reportText('mood'))},
          data: MOOD_SCORES,
          borderColor: '#797298',
          backgroundColor: 'rgba(121,114,152,0.12)',
          borderWidth: 2,
          pointRadius: 3,
          pointBackgroundColor: '#797298',
          tension: 0.4,
          fill: true,
        }]
      },
      options: {
        responsive: true, maintainAspectRatio: false,
        plugins: { legend: { display: false } },
        scales: {
          y: { min: 0, max: 10, grid: { color: '#f0eef8' }, ticks: { font: { size: 11 } } },
          x: { grid: { display: false }, ticks: { font: { size: 11 } } }
        }
      }
    });
  }
  if (SLEEP_HOURS.length >= 2) {
    new Chart(document.getElementById('sleepChart'), {
      type: 'bar',
      data: {
        labels: SLEEP_LABELS,
        datasets: [
          { label: ${reportScriptValue(reportText('sleepHours'))}, data: SLEEP_HOURS, backgroundColor: 'rgba(56,189,248,0.7)', borderRadius: 6, yAxisID: 'y' },
          { label: ${reportScriptValue(reportText('quality'))}, data: SLEEP_QUALITY, type: 'line', borderColor: '#f59e0b', pointBackgroundColor: '#f59e0b', borderWidth: 2, pointRadius: 3, tension: 0.4, yAxisID: 'y2' }
        ]
      },
      options: {
        responsive: true, maintainAspectRatio: false,
        plugins: { legend: { position: 'top', labels: { font: { size: 11 }, boxWidth: 12 } } },
        scales: {
          y:  { min: 0, max: 12, grid: { color: '#f0eef8' }, ticks: { font: { size: 11 } }, title: { display: true, text: ${reportScriptValue(reportText('hoursAxis'))}, font: { size: 10 } } },
          y2: { min: 0, max: 10, position: 'right', grid: { display: false }, ticks: { font: { size: 11 } }, title: { display: true, text: ${reportScriptValue(reportText('qualityAxis'))}, font: { size: 10 } } },
          x: { grid: { display: false }, ticks: { font: { size: 11 } } }
        }
      }
    });
  }
});
<\/script>
</body>
</html>`;

    const win = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
}

window.downloadAsPDF = downloadAsPDF;
window.downloadAsTXT = downloadAsTXT;
